### ISSUE TITLE
Button styles in dropdown

### ISSUE THREAD

**Issue by linostin** [valeriamrk/nftplatform#11]
src/components/molecules/dropdown/styles.js
<img width="382" alt="Screenshot 2022-07-02 at 18 42 48" src="https://user-images.githubusercontent.com/42766161/177007258-9512c847-d738-4b18-954a-55b1cc44c246.png">

Button with special dropdown styles not included to dropdown component. You change default styles for component button.

**Comment by valeriamrk** [comment]
this component is not used in project at all, so I deleted it
https://github.com/valeriamrk/nftplatform/commit/24806b0311f8758a9bef0416ad78dff7950f284b
