### ISSUE TITLE
Unused events props

### ISSUE THREAD

**Issue by linostin** [valeriamrk/nftplatform#14]
**For example:**
src/components/molecules/logoGroup/LogoGroup.jsx
<img width="727" alt="Screenshot 2022-07-02 at 19 04 22" src="https://user-images.githubusercontent.com/42766161/177007913-b92bd39c-d2b1-4559-ac33-b1cab99be6ce.png">

Check this in all project

**Comment by valeriamrk** [comment]
fixed
https://github.com/valeriamrk/nftplatform/commit/24806b0311f8758a9bef0416ad78dff7950f284b
