### ISSUE TITLE
Div tag for text

### ISSUE THREAD

**Issue by linostin** [valeriamrk/nftplatform#15]
src/components/organisms/accordion/Accordion.jsx
<img width="465" alt="Screenshot 2022-07-02 at 19 12 39" src="https://user-images.githubusercontent.com/42766161/177008192-a4b1071f-80c7-4bea-a162-04cde20dbfc2.png">
Check all file.
Maybe you can use span?

**Comment by valeriamrk** [comment]
fixed
https://github.com/valeriamrk/nftplatform/commit/24806b0311f8758a9bef0416ad78dff7950f284b
