### ISSUE TITLE
Box and flex

### ISSUE THREAD

**Issue by linostin** [valeriamrk/nftplatform#16]
<img width="200" alt="Screenshot 2022-07-02 at 19 40 23" src="https://user-images.githubusercontent.com/42766161/177009016-f03110c8-576c-47b1-8c36-1e6cbb6c846d.png">

Do you use it?

**Comment by valeriamrk** [comment]
it' s not used, so I deleted it
https://github.com/valeriamrk/nftplatform/commit/24806b0311f8758a9bef0416ad78dff7950f284b
