### ISSUE TITLE
Layout folder

### ISSUE THREAD

**Issue by linostin** [valeriamrk/nftplatform#19]
<img width="327" alt="Screenshot 2022-07-03 at 00 51 40" src="https://user-images.githubusercontent.com/42766161/177017090-c28f0027-cfb1-455e-8c49-6ed9cd4a0eb6.png">

**Expected result:**
src/layouts

**Comment by valeriamrk** [comment]
fixed
https://github.com/valeriamrk/nftplatform/commit/24806b0311f8758a9bef0416ad78dff7950f284b
