### ISSUE TITLE
Inspect your code to find not usable files in prod

### ISSUE THREAD

**Issue by linostin** [valeriamrk/nftplatform#2]
![image](https://user-images.githubusercontent.com/42766161/176306209-891b6594-856d-466f-9df7-da067a508f4a.png)

**For example** 
App.css
App.test.js
logo.svg
setupTests.js

Inspect all files in your project

**Comment by valeriamrk** [comment]
fixed
https://github.com/valeriamrk/nftplatform/commit/7322f8cf128b4aae8a540419f45d39b29e78d76d
