### ISSUE TITLE
Warnings in node terminal

### ISSUE THREAD

**Issue by linostin** [valeriamrk/nftplatform#22]
![image](https://user-images.githubusercontent.com/42766161/177410001-e548ce7a-b123-4b17-aa5a-a76e4774332a.png)

Check warnings in terminal after start project

**Comment by valeriamrk** [comment]
some warnings fixed
href attributes, useEffect dependency, OpenCard doesn't work correctly if eliminate warnings
https://github.com/valeriamrk/nftplatform/commit/4d3003e81743970bd8b382a9a45bb4e2687a8d98
