### ISSUE TITLE
Commented code parts in prod

### ISSUE THREAD

**Issue by linostin** [valeriamrk/nftplatform#4]
**For example:**
![image](https://user-images.githubusercontent.com/42766161/176312340-5741e96e-82c8-4244-b61e-d3c4adca7638.png)

**Files:**
src\components\presentational\atoms\headerItem\styles.js
src\components\presentational\atoms\inputField\styles.js
src\components\presentational\atoms\myButton\styles.js

src\components\presentational\molecules\dropdown\styles.js

src\components\presentational\molecules\footerNavGroup\styles.js
src\components\presentational\molecules\headerItemGroup\styles.js
src\components\presentational\molecules\logoGroup\styles.js

src\components\presentational\organisms\accordion\styles.js
src\components\presentational\organisms\cardOptions\styles.js
src\components\presentational\organisms\globalSearch\styles.js
src\components\presentational\organisms\helpItems\styles.js
src\components\presentational\organisms\hero\styles.js
src\components\presentational\organisms\modal\styles.js
src\components\presentational\organisms\nftCard\styles.js
src\components\presentational\organisms\sideNavigationBar\styles.js
src\components\presentational\organisms\topNftTable\styles.js
src\components\presentational\organisms\walletList\styles.js

src\components\presentational\pages\createPage\styles.js
src\components\presentational\pages\notFound\styles.js

**Comment by valeriamrk** [comment]
fixed
https://github.com/valeriamrk/nftplatform/commit/7322f8cf128b4aae8a540419f45d39b29e78d76d
