### ISSUE TITLE
Check all files with Prettier

### ISSUE THREAD

**Issue by linostin** [valeriamrk/nftplatform#6]
A lot of Files with incorrect code style

For example:
file MainPage.jsx
indents on line 39
**Current result:**
![image](https://user-images.githubusercontent.com/42766161/176553686-331b5de2-d479-43ad-8718-471642603930.png)
**Expected result:**
![image](https://user-images.githubusercontent.com/42766161/176553814-bc870212-8dd1-410b-8ab9-bd38e5316718.png)

**Comment by valeriamrk** [comment]
fixed
https://github.com/valeriamrk/nftplatform/commit/39a263ec5306c86ee99a924f6a636be40c221e38
